name: Publish Docker Image

on:
  push:
    branches:
      - main   # roda sempre que houver push no branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build da imagem e push para o Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            carneirojeanl/jean-lucas-mood-script-ai-agent:latest
            carneirojeanl/jean-lucas-mood-script-ai-agent:${{ github.sha }}
